import type { PaymentStatus, QuoteStatus } from '@prisma/client';
import type { FastifyInstance } from 'fastify';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { buildApp } from '../../app.js';
import type { ErrorResponse } from '../../shared/errors/error-response.js';
import type { FinanceRepository } from './finance.repository.js';
import type { ListQuotesFilters, PaymentEntity, PaymentWriteData, PaymentWriteResult, QuoteEntity, QuoteStatusResult, QuoteWriteData } from './finance.types.js';

const QUOTE_ID = '11111111-1111-4111-8111-111111111111'; const REQUEST_ID = '22222222-2222-4222-8222-222222222222'; const PAYMENT_ID = '33333333-3333-4333-8333-333333333333'; const USER_ID = '44444444-4444-4444-8444-444444444444'; const date = new Date('2026-08-05T12:00:00.000Z');
function quote(status: QuoteStatus = 'DRAFT'): QuoteEntity { return { id: QUOTE_ID, serviceRequestId: REQUEST_ID, subtotalCents: 10_000, discountCents: 1_000, totalCents: 9_000, description: null, notes: null, status, validUntil: null, approvedAt: null, rejectedAt: null, cancelledAt: null, createdAt: date, updatedAt: date, serviceRequest: { id: REQUEST_ID, status: 'QUOTED', description: 'Repair', customer: { id: USER_ID, name: 'João', phone: '61999999999', email: null }, service: { id: USER_ID, name: 'Electrical', slug: 'electrical', category: 'HOME' } } }; }
function payment(status: PaymentStatus = 'PENDING'): PaymentEntity { return { id: PAYMENT_ID, quoteId: QUOTE_ID, amountCents: 9_000, method: 'PIX', status, paidAt: status === 'PAID' ? date : null, reference: null, notes: null, createdAt: date, updatedAt: date }; }
class RouteRepository implements FinanceRepository {
  current: QuoteEntity | null = quote(); payments: PaymentEntity[] = [];
  createQuote(_id: string, input: QuoteWriteData) { if (this.current !== null) return Promise.resolve({ outcome: 'already_exists' } as const); this.current = { ...quote(), ...input }; return Promise.resolve({ outcome: 'created', quote: this.current } as const); }
  listQuotes(input: ListQuotesFilters) { void input; return Promise.resolve({ data: this.current === null ? [] : [this.current], total: this.current === null ? 0 : 1 }); }
  findQuoteById(id: string) { return Promise.resolve(this.current?.id === id ? this.current : null); }
  updateQuote(_id: string, input: Partial<QuoteWriteData>) { if (this.current === null) return Promise.resolve({ outcome: 'not_found' } as const); if (this.current.status !== 'DRAFT') return Promise.resolve({ outcome: 'not_editable', status: this.current.status } as const); Object.assign(this.current, input); return Promise.resolve({ outcome: 'updated', quote: this.current } as const); }
  updateQuoteStatus(_id: string, expected: QuoteStatus, next: QuoteStatus, at: Date): Promise<QuoteStatusResult> { if (this.current === null) return Promise.resolve({ outcome: 'not_found' }); if (this.current.status !== expected) return Promise.resolve({ outcome: 'stale', status: this.current.status }); Object.assign(this.current, { status: next, approvedAt: next === 'APPROVED' ? at : null }); return Promise.resolve({ outcome: 'updated', quote: this.current }); }
  paidTotal(id: string) { void id; return Promise.resolve(this.payments.filter((item) => item.status === 'PAID').reduce((sum, item) => sum + item.amountCents, 0)); }
  listPayments(id: string) { return Promise.resolve(this.current?.id === id ? this.payments : null); }
  findPaymentById(id: string) { return Promise.resolve(this.payments.find((item) => item.id === id) ?? null); }
  createPayment(id: string, input: PaymentWriteData): Promise<PaymentWriteResult> { if (this.current?.id !== id) return Promise.resolve({ outcome: 'quote_not_found' }); if (this.current.status !== 'APPROVED') return Promise.resolve({ outcome: 'quote_not_approved' }); const created = { ...payment(input.status), ...input }; this.payments.push(created); return Promise.resolve({ outcome: 'created', payment: created }); }
  updatePaymentStatus(id: string, expected: PaymentStatus, next: PaymentStatus, paidAt: Date | null): Promise<PaymentWriteResult> { const current = this.payments.find((item) => item.id === id); if (current === undefined) return Promise.resolve({ outcome: 'payment_not_found' }); if (current.status !== expected) return Promise.resolve({ outcome: 'stale', status: current.status }); Object.assign(current, { status: next, paidAt }); return Promise.resolve({ outcome: 'updated', payment: current }); }
}
const apps = new Set<FastifyInstance>(); let repository: RouteRepository;
function app() { const instance = buildApp({ logger: false, financeRepository: repository }); apps.add(instance); return instance; }
async function headers(role: 'ADMIN' | 'OPERATOR') { const instance = app(); await instance.ready(); return { authorization: `Bearer ${instance.jwt.sign({ sub: USER_ID, role })}` }; }
beforeEach(() => { repository = new RouteRepository(); }); afterEach(async () => { await Promise.all([...apps].map(async (instance) => instance.close())); apps.clear(); });

describe('finance routes', () => {
  it('requires authentication for every financial read', async () => { expect((await app().inject('/quotes')).statusCode).toBe(401); expect((await app().inject(`/quotes/${QUOTE_ID}`)).statusCode).toBe(401); expect((await app().inject(`/quotes/${QUOTE_ID}/payments`)).statusCode).toBe(401); });
  it('allows both roles to list, get, create and edit drafts', async () => { for (const role of ['ADMIN', 'OPERATOR'] as const) { repository.current = quote(); const auth = await headers(role); expect((await app().inject({ url: '/quotes', headers: auth })).statusCode).toBe(200); expect((await app().inject({ url: `/quotes/${QUOTE_ID}`, headers: auth })).json()).toMatchObject({ totalCents: 9_000, paymentStatus: 'UNPAID' }); expect((await app().inject({ method: 'PATCH', url: `/quotes/${QUOTE_ID}`, headers: auth, payload: { subtotalCents: 11_000 } })).json()).toMatchObject({ totalCents: 10_000 }); } });
  it('creates a quote without accepting client totals and rejects extra fields', async () => { repository.current = null; const auth = await headers('OPERATOR'); const created = await app().inject({ method: 'POST', url: '/quotes', headers: auth, payload: { serviceRequestId: REQUEST_ID, subtotalCents: 10_000, discountCents: 1_000 } }); expect(created.statusCode).toBe(201); expect(created.json()).toMatchObject({ totalCents: 9_000 }); const extra = await app().inject({ method: 'POST', url: '/quotes', headers: auth, payload: { serviceRequestId: REQUEST_ID, subtotalCents: 10_000, totalCents: 1 } }); expect(extra.statusCode).toBe(400); });
  it('restricts status and payment mutations to ADMIN', async () => { const operator = await headers('OPERATOR'); expect((await app().inject({ method: 'PATCH', url: `/quotes/${QUOTE_ID}/status`, headers: operator, payload: { status: 'SENT' } })).statusCode).toBe(403); repository.current!.status = 'APPROVED'; expect((await app().inject({ method: 'POST', url: `/quotes/${QUOTE_ID}/payments`, headers: operator, payload: { amountCents: 9_000, method: 'PIX' } })).statusCode).toBe(403); });
  it('supports the approved quote payment lifecycle for ADMIN', async () => { repository.current!.status = 'APPROVED'; const admin = await headers('ADMIN'); const created = await app().inject({ method: 'POST', url: `/quotes/${QUOTE_ID}/payments`, headers: admin, payload: { amountCents: 9_000, method: 'PIX', status: 'PENDING' } }); expect(created.statusCode).toBe(201); const paid = await app().inject({ method: 'PATCH', url: `/payments/${PAYMENT_ID}/status`, headers: admin, payload: { status: 'PAID' } }); expect(paid.json<{ paidAt: string | null }>()).toMatchObject({ status: 'PAID' }); expect(paid.json<{ paidAt: string | null }>().paidAt).not.toBeNull(); expect((await app().inject({ url: `/quotes/${QUOTE_ID}/payments`, headers: admin })).json()).toHaveLength(1); const body = (await app().inject({ url: `/payments/${PAYMENT_ID}`, headers: admin })).json<Record<string, unknown>>(); expect(body).not.toHaveProperty('quote'); expect(body).not.toHaveProperty('cardNumber'); });
  it('returns stable 404 and 409 errors and strict validation', async () => { const admin = await headers('ADMIN'); const missing = await app().inject({ url: '/quotes/99999999-9999-4999-8999-999999999999', headers: admin }); expect(missing.json<ErrorResponse>().error.code).toBe('QUOTE_NOT_FOUND'); const duplicate = await app().inject({ method: 'POST', url: '/quotes', headers: admin, payload: { serviceRequestId: REQUEST_ID, subtotalCents: 10 } }); expect(duplicate.statusCode).toBe(409); expect(duplicate.json<ErrorResponse>().error.code).toBe('QUOTE_ALREADY_EXISTS'); const empty = await app().inject({ method: 'PATCH', url: `/quotes/${QUOTE_ID}`, headers: admin, payload: {} }); expect(empty.statusCode).toBe(400); });
});
